### ISSUE TITLE
why not use node

### ISSUE THREAD

**Issue by zarlo** [developer-variety/EZLib-PHP#1]

**Comment by developer-variety** [comment]
I'm not sure what the benefits would be using Node would be?

**Comment by zarlo** [comment]
also if you dont like slim you can use Lumen (https://lumen.laravel.com) its a lot more simple

**Comment by developer-variety** [comment]
Hey @zarlo , I'll be looking into this framework later tonight.

**Comment by developer-variety** [comment]
I've decided to go with Slim after all the trouble it has given me. I've read documentation over and over that I'm good with it right now. I will not be using Twig as many prefer because I honestly just dislike it. I'll be using PHP-View, but if people don't like it they are more than welcome to fork and do changes.

I'll be closing this issue, if you have anymore concerns about this you can send me an email at developer.variety@gmail.com

Sincerely, Justin.
