### ISSUE TITLE
Testing Database ORM

### ISSUE THREAD

**Issue by francescobianco** [developer-variety/EZLib-PHP#3]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by developer-variety** [comment]
Hey @francescobianco do you happen to have Discord? I would like to ask you some questions, thanks.

**Comment by francescobianco** [comment]
you might be so kind to testing the library I talked about before

**Comment by developer-variety** [comment]
I have decided to go with Eloquent. I find it more comfortable to use because of course, I've used it before. I look at the repo, and there isn't really much documentation on how to get started.

I'll be closing this issue, if you have anymore concerns about this you can send me an email at developer.variety@gmail.com

Sincerely, Justin.

**Comment by francescobianco** [comment]
@developer-variety take a look on this a challenge between Eloqeunt and Moldable
https://github.com/javanile/moldable/wiki/Comparison:-Moldable-ORM-vs-Laravel-Eloquent
